[general]
context=default
bindport=5060
bindaddr=0.0.0.0
srvlookup=no
disallow=all
allow=ulaw
allow=alaw
nat=no
qualify=yes

[1001]
type=friend
secret=secret1
host=dynamic
context=default
callerid=Phone1 <1001>
qualify=yes

[1002]
type=friend
secret=secret2
host=dynamic
context=default
callerid=Phone2 <1002>
qualify=yes
