# Public
server {
    listen 80 default_server;
    server_name extranet.corentinpradier.com;

    location / {
        root /usr/share/nginx/html/public;
        index index.html;
    }
}

# Intranet
server {
    listen 6767 default_server;
    server_name intranet.corentinpradier.com;

    location / {
        root /usr/share/nginx/html/intranet;
        index index.html;
    }
}